* configure.in - Fixed a bug where failure to detect wx static libs would wipe out the WX_LIBS variable, resulting in linking failure - Abort if we fail to configure Box Backup properly
git-svn-id: https://svn.code.sf.net/p/boxi/code/trunk/boxi@72 bde4d9af-c013-0410-a270-fa18cafdf79f

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -36,7 +36,7 @@ AM_PATH_WXCONFIG(2.3.2, wxWin=1)
                AC_LANG_CPLUSPLUS
                AC_TRY_LINK([#include <wx/wx.h>],
                [wxString test=""],
-               ,[WX_LIBS=$WX_LIBS_STATIC])
+               ,[])
                AC_LANG_RESTORE
                LIBS=$ac_save_LIBS
                CXXFLAGS=$ac_save_CXXFLAGS
@@ -45,12 +45,15 @@ AM_PATH_WXCONFIG(2.3.2, wxWin=1)
 dnl Checks for programs.
 dnl Checks for libraries.
 # extract boxbackup in release build
-(
+if ! (
 	cd boxbackup || exit 1
 	# PATCH IN RELEASE
 	./configure || exit 1
 	mv Makefile Makefile.in || exit 1
-)
+); then
+	echo "Failed to configure Box Backup, aborting!"
+	exit 1
+fi
 
 dnl Checks for header files.
 dnl Checks for typedefs, structures, and compiler characteristics.
